# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.exception_listener:
        class: AppBundle\Exception\ApiExceptionListener
        arguments: ["@logger"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    repository.building:
        class: AppBundle\Repository\BuildingRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Building

    repository.organization:
        class: AppBundle\Repository\OrganizationRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Organization

    repository.rubric:
        class: AppBundle\Repository\RubricRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Rubric

    api.controller.building:
        class: AppBundle\Controller\BuildingController
        arguments: ['@repository.building']

    api.controller.organization:
        class: AppBundle\Controller\OrganizationController
        arguments: ['@repository.organization']

    api.controller.rubric:
        class: AppBundle\Controller\RubricController
        arguments: ['@repository.rubric']
